from enum import IntEnum


class RuntimeEvent(IntEnum):
    RUNTIME_ENABLED = 1
    CONFIG_RELOADED = 2
    RUNTIME_DISABLED = 3
    RUNTIME_STOPPED = 4
    RUNTIME_ERROR = 5
    DOWNLOAD_STARTED = 6
    DOWNLOAD_FINISHED = 7
    DOWNLOAD_FAILED = 8
    FILE_SAVE_FINISHED = 9
    FILE_SAVE_ERROR = 10
    FILE_LOAD_FINISHED = 11
    FILE_LOAD_ERROR = 12