#!/bin/sh
set -e

purge_files()
{
    for i in $(ls /home)
    do
        path=/home/$i/.config/
        if [ -h $path/autostart/opensnitch_ui.desktop -o -f $path/autostart/opensnitch_ui.desktop ];then
            rm -f $path/autostart/opensnitch_ui.desktop
        fi
        if [ -d $path/opensnitch/ ]; then
            rm -rf $path/opensnitch/
        fi
    done

    deskfile=/etc/xdg/autostart/opensnitch_ui.desktop
    if [ -h $deskfile -o -f $deskfile ]; then
        rm -f $deskfile
    fi
}

pkill -15 opensnitch-ui || true

case "$1" in
    purge)
        purge_files
        ;;
    remove)
        purge_files
        ;;
esac
