
def connect_all(win):
    win.acceptButton.clicked.connect(win.cb_accept_button_clicked)
    win.applyButton.clicked.connect(win.cb_apply_button_clicked)
    win.cancelButton.clicked.connect(win.cb_cancel_button_clicked)
    win.helpButton.clicked.connect(win.cb_help_button_clicked)
    win.popupsCheck.clicked.connect(win.cb_popups_check_toggled)
    win.dbFileButton.clicked.connect(win.cb_file_db_clicked)
    win.cmdTimeoutUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUITimeout, win.SUM))
    win.cmdTimeoutDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUITimeout, win.REST))
    win.cmdRefreshUIUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUIRefresh, win.SUM))
    win.cmdRefreshUIDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUIRefresh, win.REST))
    win.cmdUIDensityUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUIDensity, win.SUM))
    win.cmdUIDensityDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinUIDensity, win.REST))
    win.cmdGrpcWorkersUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinGrpcMaxWorkers, win.REST))
    win.cmdGrpcWorkersDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinGrpcMaxWorkers, win.SUM))
    win.cmdGrpcClientsUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinGrpcMaxClients, win.REST))
    win.cmdGrpcClientsDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinGrpcMaxClients, win.SUM))
    win.cmdNodeGcUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinNodeGC, win.SUM))
    win.cmdNodeGcDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinNodeGC, win.REST))
    win.cmdNodeRulesPath.clicked.connect(win.cb_cmd_node_rulespath_clicked)
    win.cmdDBMaxDaysUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinDBMaxDays, win.SUM))
    win.cmdDBMaxDaysDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinDBMaxDays, win.REST))
    win.cmdDBPurgesUp.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinDBPurgeInterval, win.SUM))
    win.cmdDBPurgesDown.clicked.connect(lambda: win.cb_cmd_spin_clicked(win.spinDBPurgeInterval, win.REST))
    win.cmdTestNotifs.clicked.connect(win.cb_test_notifs_clicked)
    win.radioSysNotifs.clicked.connect(win.cb_radio_system_notifications)

    win.comboNodes.currentIndexChanged.connect(win.cb_node_combo_changed)
    win.comboNodeAction.currentIndexChanged.connect(win.cb_node_needs_update)
    #win.comboNodeDuration.currentIndexChanged.connect(win.cb_node_needs_update)
    win.comboNodeMonitorMethod.currentIndexChanged.connect(win.cb_node_needs_update)
    win.comboNodeLogLevel.currentIndexChanged.connect(win.cb_node_needs_update)
    win.comboNodeLogFile.currentIndexChanged.connect(win.cb_node_needs_update)
    win.checkNodeLogUTC.clicked.connect(win.cb_node_needs_update)
    win.checkNodeLogMicro.clicked.connect(win.cb_node_needs_update)
    win.comboNodeAddress.currentTextChanged.connect(win.cb_node_needs_update)
    win.comboServerAddr.currentTextChanged.connect(win.cb_node_needs_update)
    win.spinGrpcMaxWorkers.valueChanged.connect(win.cb_node_needs_update)
    win.spinGrpcMaxClients.valueChanged.connect(win.cb_node_needs_update)
    win.checkInterceptUnknown.clicked.connect(win.cb_node_needs_update)
    win.checkApplyToNodes.clicked.connect(win.cb_node_needs_update)
    win.comboNodeAction.currentIndexChanged.connect(win.cb_node_needs_update)
    win.checkNodeAuthSkipVerify.clicked.connect(win.cb_node_needs_update)
    win.comboNodeAuthVerifyType.currentIndexChanged.connect(win.cb_node_needs_update)
    win.enableChecksums.clicked.connect(win.cb_node_needs_update)
    win.checkNodeFlushConns.clicked.connect(win.cb_node_needs_update)
    win.checkNodeBypassQueue.clicked.connect(win.cb_node_needs_update)
    win.spinNodeGC.valueChanged.connect(win.cb_node_needs_update)
    win.lineNodeMaxEvents.textChanged.connect(win.cb_node_needs_update)
    win.lineNodeMaxStats.textChanged.connect(win.cb_node_needs_update)
    win.lineNodeFwMonInterval.textChanged.connect(win.cb_node_needs_update)
    win.lineNodeRulesPath.textChanged.connect(win.cb_node_needs_update)

    win.comboAuthType.currentIndexChanged.connect(win.cb_combo_auth_type_changed)
    win.comboNodeAuthType.currentIndexChanged.connect(win.cb_combo_node_auth_type_changed)

    win.lineCACertFile.textChanged.connect(win.cb_line_certs_changed)
    win.lineCertFile.textChanged.connect(win.cb_line_certs_changed)
    win.lineCertKeyFile.textChanged.connect(win.cb_line_certs_changed)
    win.lineNodeCACertFile.textChanged.connect(win.cb_node_line_certs_changed)
    win.lineNodeCertFile.textChanged.connect(win.cb_node_line_certs_changed)
    win.lineNodeCertKeyFile.textChanged.connect(win.cb_node_line_certs_changed)

    win.lineUIScreenFactor.textChanged.connect(win.cb_ui_screen_factor_changed)
    win.checkUIRules.toggled.connect(win.cb_ui_check_rules_toggled)
    win.checkUIAutoScreen.toggled.connect(win.cb_ui_check_auto_scale_toggled)
    win.comboUITheme.currentIndexChanged.connect(win.cb_combo_themes_changed)
    win.spinUIDensity.valueChanged.connect(win.cb_spin_uidensity_changed)

    win.comboDBType.currentIndexChanged.connect(win.cb_db_type_changed)
    win.checkDBMaxDays.toggled.connect(win.cb_db_max_days_toggled)
    win.checkDBJrnlWal.toggled.connect(win.cb_db_jrnl_wal_toggled)
