name: Linux Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.12, 1.17]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create a network namespace for privileged tests
      run: sudo ip netns add unpriv0

    - name: Build test binary for privileged tests
      run: go test -c -race .

    - name: Run privileged tests
      run: sudo ./netlink.test -test.v -test.run TestIntegration*
