# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ui_pb2 as ui__pb2


class UIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/protocol.UI/Ping',
        request_serializer=ui__pb2.PingRequest.SerializeToString,
        response_deserializer=ui__pb2.PingReply.FromString,
        )
    self.AskRule = channel.unary_unary(
        '/protocol.UI/AskRule',
        request_serializer=ui__pb2.Connection.SerializeToString,
        response_deserializer=ui__pb2.Rule.FromString,
        )


class UIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AskRule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=ui__pb2.PingRequest.FromString,
          response_serializer=ui__pb2.PingReply.SerializeToString,
      ),
      'AskRule': grpc.unary_unary_rpc_method_handler(
          servicer.AskRule,
          request_deserializer=ui__pb2.Connection.FromString,
          response_serializer=ui__pb2.Rule.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protocol.UI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
