// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ui.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	ui.proto

It has these top-level messages:
	Statistics
	PingRequest
	PingReply
	RuleRequest
	RuleOperator
	RuleReply
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Statistics struct {
	DaemonVersion string            `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion" json:"daemon_version,omitempty"`
	Uptime        uint64            `protobuf:"varint,2,opt,name=uptime" json:"uptime,omitempty"`
	DnsResponses  uint64            `protobuf:"varint,3,opt,name=dns_responses,json=dnsResponses" json:"dns_responses,omitempty"`
	Connections   uint64            `protobuf:"varint,4,opt,name=connections" json:"connections,omitempty"`
	Ignored       uint64            `protobuf:"varint,5,opt,name=ignored" json:"ignored,omitempty"`
	Accepted      uint64            `protobuf:"varint,6,opt,name=accepted" json:"accepted,omitempty"`
	Dropped       uint64            `protobuf:"varint,7,opt,name=dropped" json:"dropped,omitempty"`
	RuleHits      uint64            `protobuf:"varint,8,opt,name=rule_hits,json=ruleHits" json:"rule_hits,omitempty"`
	RuleMisses    uint64            `protobuf:"varint,9,opt,name=rule_misses,json=ruleMisses" json:"rule_misses,omitempty"`
	ByProto       map[string]uint64 `protobuf:"bytes,10,rep,name=by_proto,json=byProto" json:"by_proto,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByAddress     map[string]uint64 `protobuf:"bytes,11,rep,name=by_address,json=byAddress" json:"by_address,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByHost        map[string]uint64 `protobuf:"bytes,12,rep,name=by_host,json=byHost" json:"by_host,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByPort        map[string]uint64 `protobuf:"bytes,13,rep,name=by_port,json=byPort" json:"by_port,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByUid         map[string]uint64 `protobuf:"bytes,14,rep,name=by_uid,json=byUid" json:"by_uid,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByExecutable  map[string]uint64 `protobuf:"bytes,15,rep,name=by_executable,json=byExecutable" json:"by_executable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *Statistics) Reset()                    { *m = Statistics{} }
func (m *Statistics) String() string            { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()               {}
func (*Statistics) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Statistics) GetDaemonVersion() string {
	if m != nil {
		return m.DaemonVersion
	}
	return ""
}

func (m *Statistics) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *Statistics) GetDnsResponses() uint64 {
	if m != nil {
		return m.DnsResponses
	}
	return 0
}

func (m *Statistics) GetConnections() uint64 {
	if m != nil {
		return m.Connections
	}
	return 0
}

func (m *Statistics) GetIgnored() uint64 {
	if m != nil {
		return m.Ignored
	}
	return 0
}

func (m *Statistics) GetAccepted() uint64 {
	if m != nil {
		return m.Accepted
	}
	return 0
}

func (m *Statistics) GetDropped() uint64 {
	if m != nil {
		return m.Dropped
	}
	return 0
}

func (m *Statistics) GetRuleHits() uint64 {
	if m != nil {
		return m.RuleHits
	}
	return 0
}

func (m *Statistics) GetRuleMisses() uint64 {
	if m != nil {
		return m.RuleMisses
	}
	return 0
}

func (m *Statistics) GetByProto() map[string]uint64 {
	if m != nil {
		return m.ByProto
	}
	return nil
}

func (m *Statistics) GetByAddress() map[string]uint64 {
	if m != nil {
		return m.ByAddress
	}
	return nil
}

func (m *Statistics) GetByHost() map[string]uint64 {
	if m != nil {
		return m.ByHost
	}
	return nil
}

func (m *Statistics) GetByPort() map[string]uint64 {
	if m != nil {
		return m.ByPort
	}
	return nil
}

func (m *Statistics) GetByUid() map[string]uint64 {
	if m != nil {
		return m.ByUid
	}
	return nil
}

func (m *Statistics) GetByExecutable() map[string]uint64 {
	if m != nil {
		return m.ByExecutable
	}
	return nil
}

type PingRequest struct {
	Id    uint64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Stats *Statistics `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PingRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PingRequest) GetStats() *Statistics {
	if m != nil {
		return m.Stats
	}
	return nil
}

type PingReply struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PingReply) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RuleRequest struct {
	Protocol    string   `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	SrcIp       string   `protobuf:"bytes,2,opt,name=src_ip,json=srcIp" json:"src_ip,omitempty"`
	SrcPort     uint32   `protobuf:"varint,3,opt,name=src_port,json=srcPort" json:"src_port,omitempty"`
	DstIp       string   `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp" json:"dst_ip,omitempty"`
	DstHost     string   `protobuf:"bytes,5,opt,name=dst_host,json=dstHost" json:"dst_host,omitempty"`
	DstPort     uint32   `protobuf:"varint,6,opt,name=dst_port,json=dstPort" json:"dst_port,omitempty"`
	UserId      uint32   `protobuf:"varint,7,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ProcessId   uint32   `protobuf:"varint,8,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	ProcessPath string   `protobuf:"bytes,9,opt,name=process_path,json=processPath" json:"process_path,omitempty"`
	ProcessArgs []string `protobuf:"bytes,10,rep,name=process_args,json=processArgs" json:"process_args,omitempty"`
}

func (m *RuleRequest) Reset()                    { *m = RuleRequest{} }
func (m *RuleRequest) String() string            { return proto.CompactTextString(m) }
func (*RuleRequest) ProtoMessage()               {}
func (*RuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RuleRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *RuleRequest) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *RuleRequest) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *RuleRequest) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

func (m *RuleRequest) GetDstHost() string {
	if m != nil {
		return m.DstHost
	}
	return ""
}

func (m *RuleRequest) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *RuleRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RuleRequest) GetProcessId() uint32 {
	if m != nil {
		return m.ProcessId
	}
	return 0
}

func (m *RuleRequest) GetProcessPath() string {
	if m != nil {
		return m.ProcessPath
	}
	return ""
}

func (m *RuleRequest) GetProcessArgs() []string {
	if m != nil {
		return m.ProcessArgs
	}
	return nil
}

type RuleOperator struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Operand string `protobuf:"bytes,2,opt,name=operand" json:"operand,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *RuleOperator) Reset()                    { *m = RuleOperator{} }
func (m *RuleOperator) String() string            { return proto.CompactTextString(m) }
func (*RuleOperator) ProtoMessage()               {}
func (*RuleOperator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RuleOperator) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RuleOperator) GetOperand() string {
	if m != nil {
		return m.Operand
	}
	return ""
}

func (m *RuleOperator) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type RuleReply struct {
	Name     string        `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Action   string        `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Duration string        `protobuf:"bytes,3,opt,name=duration" json:"duration,omitempty"`
	Operator *RuleOperator `protobuf:"bytes,4,opt,name=operator" json:"operator,omitempty"`
}

func (m *RuleReply) Reset()                    { *m = RuleReply{} }
func (m *RuleReply) String() string            { return proto.CompactTextString(m) }
func (*RuleReply) ProtoMessage()               {}
func (*RuleReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RuleReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleReply) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *RuleReply) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *RuleReply) GetOperator() *RuleOperator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func init() {
	proto.RegisterType((*Statistics)(nil), "protocol.Statistics")
	proto.RegisterType((*PingRequest)(nil), "protocol.PingRequest")
	proto.RegisterType((*PingReply)(nil), "protocol.PingReply")
	proto.RegisterType((*RuleRequest)(nil), "protocol.RuleRequest")
	proto.RegisterType((*RuleOperator)(nil), "protocol.RuleOperator")
	proto.RegisterType((*RuleReply)(nil), "protocol.RuleReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UI service

type UIClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	AskRule(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleReply, error)
}

type uIClient struct {
	cc *grpc.ClientConn
}

func NewUIClient(cc *grpc.ClientConn) UIClient {
	return &uIClient{cc}
}

func (c *uIClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/protocol.UI/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uIClient) AskRule(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleReply, error) {
	out := new(RuleReply)
	err := grpc.Invoke(ctx, "/protocol.UI/AskRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UI service

type UIServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	AskRule(context.Context, *RuleRequest) (*RuleReply, error)
}

func RegisterUIServer(s *grpc.Server, srv UIServer) {
	s.RegisterService(&_UI_serviceDesc, srv)
}

func _UI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UI/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UI_AskRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIServer).AskRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UI/AskRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIServer).AskRule(ctx, req.(*RuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.UI",
	HandlerType: (*UIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _UI_Ping_Handler,
		},
		{
			MethodName: "AskRule",
			Handler:    _UI_AskRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ui.proto",
}

func init() { proto.RegisterFile("ui.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 773 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x61, 0x8f, 0xdb, 0x44,
	0x10, 0x6d, 0x72, 0x89, 0x63, 0x8f, 0x93, 0x03, 0x96, 0x5e, 0x31, 0xa9, 0x50, 0xd3, 0x54, 0xa0,
	0x13, 0x1f, 0xee, 0x43, 0x40, 0xd0, 0x56, 0x95, 0xd0, 0x55, 0xaa, 0xd4, 0x08, 0x21, 0x22, 0xa3,
	0xf2, 0xd5, 0x5a, 0x7b, 0x57, 0x77, 0xab, 0xe6, 0xbc, 0x66, 0x67, 0x5d, 0xe1, 0x5f, 0x00, 0xbf,
	0x84, 0xdf, 0x89, 0x76, 0xd6, 0x76, 0xcc, 0x41, 0x90, 0xf2, 0x29, 0xfb, 0xde, 0xcc, 0x7b, 0xb1,
	0xdf, 0x8e, 0x07, 0xc2, 0x5a, 0x5d, 0x55, 0x46, 0x5b, 0xcd, 0x42, 0xfa, 0x29, 0xf4, 0x7e, 0xfd,
	0x67, 0x08, 0xf0, 0x8b, 0xe5, 0x56, 0xa1, 0x55, 0x05, 0xb2, 0x2f, 0xe1, 0x5c, 0x70, 0x79, 0xa7,
	0xcb, 0xec, 0x83, 0x34, 0xa8, 0x74, 0x99, 0x8c, 0x56, 0xa3, 0xcb, 0x28, 0x5d, 0x78, 0xf6, 0x57,
	0x4f, 0xb2, 0x47, 0x10, 0xd4, 0x95, 0x55, 0x77, 0x32, 0x19, 0xaf, 0x46, 0x97, 0x93, 0xb4, 0x45,
	0xec, 0x19, 0x2c, 0x44, 0x89, 0x99, 0x91, 0x58, 0xe9, 0x12, 0x25, 0x26, 0x67, 0x54, 0x9e, 0x8b,
	0x12, 0xd3, 0x8e, 0x63, 0x2b, 0x88, 0x0b, 0x5d, 0x96, 0xb2, 0xb0, 0x4a, 0x97, 0x98, 0x4c, 0xa8,
	0x65, 0x48, 0xb1, 0x04, 0x66, 0xea, 0xa6, 0xd4, 0x46, 0x8a, 0x64, 0x4a, 0xd5, 0x0e, 0xb2, 0x25,
	0x84, 0xbc, 0x28, 0x64, 0x65, 0xa5, 0x48, 0x02, 0x2a, 0xf5, 0xd8, 0xa9, 0x84, 0xd1, 0x55, 0x25,
	0x45, 0x32, 0xf3, 0xaa, 0x16, 0xb2, 0xc7, 0x10, 0x99, 0x7a, 0x2f, 0xb3, 0x5b, 0x65, 0x31, 0x09,
	0xbd, 0xcc, 0x11, 0x6f, 0x95, 0x45, 0xf6, 0x04, 0x62, 0x2a, 0xde, 0x29, 0x74, 0x4f, 0x1c, 0x51,
	0x19, 0x1c, 0xf5, 0x13, 0x31, 0xec, 0x15, 0x84, 0x79, 0x93, 0x51, 0x62, 0x09, 0xac, 0xce, 0x2e,
	0xe3, 0xcd, 0xd3, 0xab, 0x2e, 0xbf, 0xab, 0x43, 0x76, 0x57, 0xaf, 0x9b, 0x9d, 0x63, 0xdf, 0x94,
	0xd6, 0x34, 0xe9, 0x2c, 0xf7, 0x88, 0xbd, 0x06, 0xc8, 0x9b, 0x8c, 0x0b, 0x61, 0x24, 0x62, 0x12,
	0x93, 0xfe, 0xd9, 0x11, 0xfd, 0xb5, 0xef, 0xf2, 0x0e, 0x51, 0xde, 0x61, 0xf6, 0x02, 0x66, 0x79,
	0x93, 0xdd, 0x6a, 0xb4, 0xc9, 0x9c, 0x0c, 0x56, 0x47, 0x0c, 0xde, 0x6a, 0xb4, 0x5e, 0x1d, 0xe4,
	0x04, 0x5a, 0x69, 0xa5, 0x8d, 0x4d, 0x16, 0xff, 0x2b, 0xdd, 0x69, 0x73, 0x90, 0x3a, 0xc0, 0xbe,
	0x83, 0x20, 0x6f, 0xb2, 0x5a, 0x89, 0xe4, 0x9c, 0x94, 0x4f, 0x8e, 0x28, 0xdf, 0x29, 0xe1, 0x85,
	0xd3, 0xdc, 0x9d, 0xd9, 0x8f, 0xb0, 0xc8, 0x9b, 0x4c, 0xfe, 0x2e, 0x8b, 0xda, 0xf2, 0x7c, 0x2f,
	0x93, 0x8f, 0x48, 0xfe, 0xd5, 0x11, 0xf9, 0x9b, 0xbe, 0xd1, 0xbb, 0xcc, 0xf3, 0x01, 0xb5, 0x7c,
	0x09, 0xf3, 0x61, 0xae, 0xec, 0x63, 0x38, 0x7b, 0x2f, 0x9b, 0x76, 0x2a, 0xdd, 0x91, 0x3d, 0x84,
	0xe9, 0x07, 0xbe, 0xaf, 0xbb, 0x51, 0xf4, 0xe0, 0xe5, 0xf8, 0xf9, 0x68, 0xf9, 0x0a, 0xce, 0xff,
	0x99, 0xe9, 0x49, 0xea, 0x17, 0x10, 0x0f, 0x02, 0x3d, 0x5d, 0xda, 0x07, 0x7a, 0x92, 0xf4, 0x39,
	0xc0, 0x21, 0xd1, 0x93, 0x94, 0x3f, 0xc0, 0x27, 0xff, 0x0a, 0xf3, 0x14, 0x83, 0xf5, 0x16, 0xe2,
	0x9d, 0x2a, 0x6f, 0x52, 0xf9, 0x5b, 0x2d, 0xd1, 0xb2, 0x73, 0x18, 0x2b, 0x41, 0xca, 0x49, 0x3a,
	0x56, 0x82, 0x7d, 0x0d, 0x53, 0xb4, 0xdc, 0x22, 0x09, 0xe3, 0xcd, 0xc3, 0xff, 0xba, 0xce, 0xd4,
	0xb7, 0xac, 0x1f, 0x43, 0xe4, 0xad, 0xaa, 0x7d, 0x73, 0xdf, 0x68, 0xfd, 0xd7, 0x18, 0xe2, 0xb4,
	0xde, 0xcb, 0xee, 0x8f, 0x96, 0xd0, 0xaf, 0xa3, 0xf6, 0x41, 0x7b, 0xcc, 0x2e, 0x20, 0x40, 0x53,
	0x64, 0xaa, 0xa2, 0x7f, 0x8d, 0xd2, 0x29, 0x9a, 0x62, 0x5b, 0xb1, 0xcf, 0x21, 0x74, 0x34, 0x8d,
	0xb5, 0x5b, 0x31, 0x8b, 0x74, 0x86, 0xa6, 0xa0, 0xa9, 0xbd, 0x80, 0x40, 0xa0, 0x75, 0x8a, 0x89,
	0x57, 0x08, 0xb4, 0x5e, 0xe1, 0x68, 0xfa, 0x86, 0xa6, 0x54, 0x98, 0x09, 0xb4, 0xf4, 0x89, 0xb4,
	0x25, 0x32, 0x0b, 0xbc, 0x99, 0x40, 0x4b, 0x66, 0x9f, 0xc1, 0xac, 0x46, 0x69, 0x32, 0xe5, 0x57,
	0xca, 0x22, 0x0d, 0x1c, 0xdc, 0x0a, 0xf6, 0x05, 0x40, 0x65, 0x74, 0x21, 0x11, 0x5d, 0x2d, 0xa4,
	0x5a, 0xd4, 0x32, 0x5b, 0xc1, 0x9e, 0xc2, 0xbc, 0x2b, 0x57, 0xdc, 0xde, 0xd2, 0x52, 0x89, 0xd2,
	0xb8, 0xe5, 0x76, 0xdc, 0xde, 0x0e, 0x5b, 0xb8, 0xb9, 0x41, 0xda, 0x2c, 0x87, 0x96, 0x6b, 0x73,
	0x83, 0xeb, 0x1d, 0xcc, 0x5d, 0x4e, 0x3f, 0x57, 0xd2, 0x70, 0xab, 0x0d, 0x63, 0x30, 0xb1, 0x4d,
	0x25, 0xdb, 0x90, 0xe8, 0xec, 0x96, 0x9e, 0x76, 0xf5, 0x52, 0xb4, 0x09, 0x75, 0xd0, 0x75, 0x0b,
	0x6e, 0x39, 0xe5, 0x13, 0xa5, 0x74, 0x5e, 0xff, 0x31, 0x82, 0xc8, 0x47, 0xef, 0x2e, 0x86, 0xc1,
	0xa4, 0xe4, 0x77, 0xbd, 0x9f, 0x3b, 0xbb, 0xcd, 0xce, 0x69, 0x0b, 0xb7, 0x76, 0x2d, 0x72, 0x97,
	0x24, 0x6a, 0xc3, 0xa9, 0xe2, 0x1d, 0x7b, 0xcc, 0x36, 0x10, 0xea, 0xf6, 0x19, 0x29, 0xf4, 0x78,
	0xf3, 0xe8, 0x30, 0x1c, 0xc3, 0x37, 0x48, 0xfb, 0xbe, 0x0d, 0xc2, 0xf8, 0xdd, 0x96, 0x7d, 0x0b,
	0x13, 0x37, 0x27, 0xec, 0xe2, 0xd0, 0x3f, 0x18, 0xc1, 0xe5, 0xa7, 0xf7, 0xe9, 0x6a, 0xdf, 0xac,
	0x1f, 0xb0, 0xef, 0x61, 0x76, 0x8d, 0xef, 0x9d, 0xf1, 0x50, 0x38, 0x18, 0xa9, 0xa1, 0xb0, 0x7f,
	0xdd, 0xf5, 0x83, 0x3c, 0x20, 0xf6, 0x9b, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xe4, 0xf0,
	0xb4, 0x09, 0x07, 0x00, 0x00,
}
