#!/bin/sh
set -e

. /usr/share/debconf/confmodule

purge_files()
{
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
    fi

    for i in $(ls /home)
    do
        path=/home/$i/.config/
        if [ -h $path/autostart/opensnitch_ui.desktop -o -f $path/autostart/opensnitch_ui.desktop ];then
            rm -f $path/autostart/opensnitch_ui.desktop
        fi
        if [ -d $path/opensnitch/ ]; then
            rm -rf $path/opensnitch/
        fi
    done
}

pkill -15 opensnitch-ui || true
db_purge

case "$1" in
    purge)
        purge_files
        ;;
    remove)
        db_purge
        ;;
esac
