#!/bin/sh

set -e

for i in $(ls /home)
do
    path=/home/$i/.config/autostart/
    if [ ! -d $path ]; then
        mkdir -p $path
    fi
    if [ -f /usr/share/applications/opensnitch_ui.desktop ];then
        cp /usr/share/applications/opensnitch_ui.desktop $path
    fi
done
