// Code generated by hand. DO NOT EDIT.

package pkg

// Methods on T2 are only defined in this generated file
// Methods on T3 and T4 are defined in this file and a non-generated file

type T2 struct{}

func (foo T2) Fn1() {}
func (bar T2) Fn2() {}

type T3 struct{}

func (foo T3) Fn1() {}

type T4 struct{}

func (foo T4) Fn1() {}
